- phase0/CRC.md
"A primary goal of the project is to demonstrate to us that you understand Clean Architecture." - Advice for phase 0
I've included our feature suggestions underneath the base specification.
I believe this is better for submission than the existing specification.md because it is simpler and will help our design. We don't have to decide what database we are using, or how a user will login, at this stage. We need to focus on making a simple specification so that the classes we implement will be on the right layer of clean architecture.
My CRC idea is also here.
I hope we keep editing and submit something along these lines.
> Suggesting spec and crc for phase 0

- src/test/java/Entity/CourseTest.java
- src/test/java/Entity/RatingTest.java
- src/test/java/Entity/UserTest.java
someone will implement the classes later
> Added tests for Course, Rating, User

- src/main/data/CourseDatabase.json
- src/main/java/Controller/Database/Database.java
- src/main/java/Controller/Database/UserDatabase.java
Add instructor name, year and rate for course
> Update course database

- src/main/java/Constants/CommandConstants.java
- src/main/java/Controller/Commands/CheckoutCommand.java
- src/main/java/Controller/Commands/Command.java
- src/main/java/Controller/Commands/CommentCommands/DisplayFullThreadCommand.java
- src/main/java/Controller/Commands/CommentCommands/DisplaySubsetThreadCommand.java
- src/main/java/Controller/Commands/CommentCommands/GetCommentsCommand.java
- src/main/java/Controller/Commands/CommentCommands/GetPathCommand.java
- src/main/java/Controller/Commands/CommentCommands/ReplyCommand.java
- src/main/java/Controller/Commands/CommentCommands/VoteCommand.java
- src/main/java/Controller/Commands/LoginCommand.java
- src/main/java/Controller/Commands/LogoutCommand.java
- src/main/java/Controller/Commands/NewUserCommand.java
- src/main/java/Controller/Commands/PrintCommand.java
- src/main/java/Controller/Commands/RateCommand.java
- src/main/java/Controller/Commands/SaveAllCommand.java
- src/main/java/Entity/Rating.java
- src/main/java/Exceptions/CommandHelpException.java
- src/main/java/UseCase/CommentManager/CommentManager.java
command checkAuthpage whatever the method is called does a bunch of checks that most commands all include. This can't be tested as of now, as coursePage isn't really done
> Added comment related commands, added new command methods

- Phase1-Design Document/Solid Design Principles.md
> Jian(fiona) li 

- Phase1-Design Document/Progress Report.md
> Create Progress Report.md

- src/main/java/Entity/StudentUser.java
Change from containsKey to get method
> Updated the getProgramDetail Method

- src/test/java/Entity/UserTest.java
Add test case for getOtherData and getProgramDetail
> Add test cases for getOtherData and getProgramDetail

- src/main/java/Entity/User.java
> Updated User Entity

- src/main/java/Entity/InstructorUser.java
- src/main/java/Entity/StudentUser.java
Fixed getPosition method and code style
> Fixed getPosition method and code style

- phase1/Progress Report.md
- src/main/java/UseCase/CourseManager/CourseManager.java
- src/main/java/UseCase/CoursePage/CoursePage.java
- src/test/java/UseCase/CourseManagerTest.java
CourseManager, CourseManagerTest and its related updates.
> Merge request from coursepage-new to main

- src/test/java/Entity/UserTest.java
Add test cases for Instructor class
> Add test cases for Instructor class

- src/test/java/UseCase/CoursePage/CoursePageTestnew.java
Add test cases for coursepage  under CoursePageTestnew
> Add test cases for coursepage  under CoursePageTestnew

- src/test/java/UseCase/CoursePage/CoursePageTestnew.java
test cases for get instructors, and get ratings methods
> Add test cases for CoursePageTestnew

- phase2/accessibility.md
Wrote the accessibility report
> Wrote the accessibility report

- src/test/java/entity/UserTest.java
> Add test cases for user

- phase2/specific-design-explanations/Classes Explanation.md
Add to entity and interface + format
> Update Classess Explanation

- phase2/Code Style and Documentation
> Update code style

- phase2/specific-design-explanations/user-factory design.md
> Update factory design

- src/main/java/controller/commands/Command.java
- src/main/java/controller/commands/commandHelpers/PageGetter.java
- src/main/java/entity/CommentGraph.java
- src/main/java/entity/Course.java
- src/main/java/outer/ScreenIO.java
- src/main/java/outer/database/Database.java
- src/main/java/usecase/CommentPresenter.java
> Proofreading

- src/main/java/entity/CommentGraph.java
PLEASE REVIEW BEFORE MERGE
I tested out the program after the warning have been fixed and do not see any issues on my end, but I could have missed something, so please review before merge.
> Addressed Warnings in CommentGraph

- src/test/java/usecase/CommentManagerTest.java
Added documentation to throw statements in java doc for CommentManagerTest.java
> Added documentation to throw statements in java doc for CommentManagerTest.java
